#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --cpus-per-task=40
#SBATCH -J vcdrate

module load jupyter
module load python/3.7

jupyter nbconvert --execute decay_rates_vac.ipynb --ExecutePreprocessor.timeout=-1
