#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=2
#SBATCH --mail-user=dpirvu@perimeterinstitute.ca
#SBATCH --mail-type=ALL
#SBATCH -J vcdeboost

python3 deboost_vac.py >> ./data/out_deboost_vac.txt &
python3 deboost_vac1.py >> ./data/out_deboost_vac1.txt &
python3 deboost_vac2.py >> ./data/out_deboost_vac2.txt &
python3 deboost_vac3.py >> ./data/out_deboost_vac3.txt &
python3 deboost_vac4.py >> ./data/out_deboost_vac4.txt &
python3 deboost_vac5.py >> ./data/out_deboost_vac5.txt &
python3 deboost_vac6.py >> ./data/out_deboost_vac6.txt &
python3 deboost_vac7.py >> ./data/out_deboost_vac7.txt &
python3 deboost_vac8.py >> ./data/out_deboost_vac8.txt &
python3 deboost_vac9.py >> ./data/out_deboost_vac9.txt &
python3 deboost_vac10.py >> ./data/out_deboost_vac10.txt &
python3 deboost_vac11.py >> ./data/out_deboost_vac11.txt &
python3 deboost_vac12.py >> ./data/out_deboost_vac12.txt &
python3 deboost_vac13.py >> ./data/out_deboost_vac13.txt &
python3 deboost_vac14.py >> ./data/out_deboost_vac14.txt &
python3 deboost_vac15.py >> ./data/out_deboost_vac15.txt &
python3 deboost_vac16.py >> ./data/out_deboost_vac16.txt &
python3 deboost_vac17.py >> ./data/out_deboost_vac17.txt &
python3 deboost_vac18.py >> ./data/out_deboost_vac18.txt &
python3 deboost_vac19.py >> ./data/out_deboost_vac19.txt &
wait

