#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=debugq
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH --time=1:00:00
#SBATCH -J vcpsbrf

python3 psbrief.py >> ./outputs/psstatus.txt


